baseurl: http://chuchencheng.com/
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post


theme: jekyll-theme-cayman